blocked:
  referrer:
    # Block Porn sites
    - uncams.com
    - xujan.com

redirect:
  # Redirect to current api version
  https://{{linked_hostname}}/4.4{{path}}:
    - https://{{linked_hostname}}/api/*
    - https://{{linked_hostname}}/v2/*

  # Redirect to primary domain
  https://{{linked_hostname}}{{path}}:
    - https://{{hostname}}/*
    - https://{{origin}}/*

header:
  remove:
    - expect-ct
    - cf-ray
    - cf-request-id
    - nel
    - report-to

cache:
  server:
    1y:
      - https://{{linked_hostname}}/*/api/*
      - https://{{linked_hostname}}/*/v2/*

  client:
    1h:
      - https://{{linked_hostname}}/
      - https://{{linked_hostname}}/*/
    30d:
      - https://{{linked_hostname}}/*/api/*
      - https://{{linked_hostname}}/*/v2/*
      - https://{{linked_hostname}}/api/*
      - https://{{linked_hostname}}/v2/*
      - https://{{linked_hostname}}/*.js
      - https://{{linked_hostname}}/*.css
      - https://{{linked_hostname}}/*.png
      - https://{{linked_hostname}}/*.jpg

origin:
  https://{{origin}}:
    - https://{{linked_hostname}}/*/api/*
    - https://{{linked_hostname}}/*/v2/*
    - https://{{linked_hostname}}/*/stats.json
