cdn:
  blocked:
    referrer:
      # Block Porn sites
      - uncams.com
      - xujan.com

  redirect:
    # Redirect to current api version
    https://{{process.env.BUNNYCDN_HOSTNAME}}/4.5{{path}}:
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/api/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/v2/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/stats.json

    # Redirect to primary domain
    https://{{process.env.BUNNYCDN_HOSTNAME}}{{path}}:
      - https://{{process.env.BUNNYCDN_PULL_ZONE_NAME}}.b-cdn.net/*
      - https://{{process.env.BUNNYCDN_ORIGIN}}/*

  header:
    remove:
      - expect-ct
      - cf-ray
      - cf-request-id
      - nel
      - report-to

  cache:
    server:
      1y:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*

    client:
      1h:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/
      30d:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/api/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/v2/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.js
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.css
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.png
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.jpg

  origin:
    https://{{process.env.BUNNYCDN_ORIGIN}}:
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/stats.json
