name: Publish Pre Release

on:
  push:
    tags:
      - v*-alpha.*
      - v*-beta.*
      - v*-rc.*

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - run: npm install
      - run: npm build
      - run: npm test

      - run:
          ./node_modules/.bin/lerna publish from-package --no-verify-access
          --dist-tag next --ignore-scripts --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
