name: Publish

on:
  push:
    tags-ignore:
      - v*-alpha.*
      - v*-beta.*
      - v*-rc.*

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build
      - run: npm run test

      - run:
          ./node_modules/.bin/lerna publish from-package
          --ignore-scripts --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
